engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    enabled: true
  rubocop:
    enabled: true
rathing:
  paths:
  - "src/**"
exclude_paths:
  - "assets/*"
  - "test/*"
  - "cryptoanalyse/*"
  - "cryptographie/*"
  
