language: Ruby
rvm:
  - 2.3

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y build-essential xorg-dev libudev-dev libts-dev libgl1-mesa-dev libglu1-mesa-dev libasound2-dev libpulse-dev libopenal-dev libogg-dev libvorbis-dev libaudiofile-dev libpng12-dev libfreetype6-dev libusb-dev libdbus-1-dev zlib1g-dev libdirectfb-dev
  - gem update --system
  - gem --version

install:
  - sudo apt-get install -y ruby-dev
  - gem install bundler
  - bundler install --without production

script:
  - rake
  - CODECLIMATE_REPO_TOKEN=3ad359967ad2924ee23cb4e0f0d10c98d6b9e1f9 bundle exec codeclimate-test-reporter


branches:
  only:
  - master

addons:
    code_climate:
        repo_token: 3ad359967ad2924ee23cb4e0f0d10c98d6b9e1f9

after_success:
- bundle exec codeclimate-test-reporter
